server.servlet.context-path=/bjapi
server.port=22512

spring.devtools.livereload.enabled=false
spring.thymeleaf.cache=false

spring.main.allow-bean-definition-overriding=true

spring.web.resources.static-locations= classpath:static/**
spring.mvc.static-path-pattern= /static/**
spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode= HTML
spring.thymeleaf.template-resolver-order=0
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location= true
