
########### postgresql

db.bj.driver=org.postgresql.Driver
db.bj.dialect=org.hibernate.dialect.PostgreSQLDialect
db.bj.url=jdbc:postgresql://localhost:5432/uctc2
db.bj.username=your_db_username
db.bj.password=your_db_password
db.bj.ddl.auto=none


api.url.floating.population.site_id=0000
api.url.floating.population.num_sequence = 2
api.url.floating.population.resolution=days
api.url.floating.population.resolution_by_hours=hours
api.url.floating.population.ip_host=https://localhost:38085/
api.url.floating.population.averageDuration_path=api/AverageDuration/
api.url.floating.population.site_id_token=Token your_api_token_here

api.url.floating.population.visitorCount_path=api/VisitorCount/
api.url.floating.population.mobility_path = api/Mobility/
api.url.floating.population.analytics_visitorCount_path = api/Analytics/VisitorCount

api.url.floating.population.user=your_api_user
api.url.floating.population.pass=your_api_password
api.url.floating.population.region_url=dashboard/api-master/Region/List/

api.ssl.device.url = https://localhost:38085/
api.ssl.device.path = dashboard/api-master/Region/List/
api.ssl.device.user = your_api_user
api.ssl.device.pass = your_api_password
api.ssl.device.site_id = 0000
api.ssl.device.authorization = Token your_api_token_here


#################oms

platform.oms.url.server = http://localhost/oms
platform.oms.url.token.alive = /api/user/chkTokenAlive
platform.oms.system.key = YOUR_SYSTEM_KEY
platform.oms.system.secret = your_oms_secret_here
platform.oms.api.sys.auth = api/user/sysAuth
platform.oms.api.sys.list = /api/user/getsysList
platform.oms.api.user.info = /api/user/info
